api1_get_jobs:
    path: "/jobs"
    defaults:
        _controller: "WjzijderveldOption3ApiBundle:Api:getJobs"
    requirements:
        _version: "1"

api1_get_job:
    path: "/jobs/{id}"
    defaults:
        _controller: "WjzijderveldOption3ApiBundle:Api:getJob"
    requirements:
        id: \d+
        _version: "1"