api1_get_jobs:
    path: "/jobs"
    defaults:
        _controller: "WjzijderveldApiBundle:Api:getJobs"
    condition: "context.getApiVersion() === '1'"

api1_get_job:
    path: "/jobs/{id}"
    defaults:
        _controller: "WjzijderveldApiBundle:Api:getJob"
    requirements:
        id: \d+
    condition: "context.getApiVersion() === '1'"
